import type { Product } from './types';

export const products: Product[] = [
  {
    id: 'prod_001',
    name: 'Vinho Tinto Cabernet',
    quantity: 30,
    expirationDate: '2025-12-20',
    averageDailySales: 2,
    daysToRestock: 10,
    imageUrl: 'https://placehold.co/400x400',
    imageHint: 'wine bottle',
  },
  {
    id: 'prod_002',
    name: 'Cerveja Artesanal IPA',
    quantity: 150,
    expirationDate: '2024-11-15',
    averageDailySales: 20,
    daysToRestock: 5,
    imageUrl: 'https://placehold.co/400x400',
    imageHint: 'beer bottle',
  },
  {
    id: 'prod_003',
    name: 'Whisky Escocês 12 Anos',
    quantity: 15,
    expirationDate: '2030-01-01',
    averageDailySales: 1,
    daysToRestock: 14,
    imageUrl: 'https://placehold.co/400x400',
    imageHint: 'whisky bottle',
  },
  {
    id: 'prod_004',
    name: 'Refrigerante de Cola',
    quantity: 20,
    expirationDate: '2024-10-30',
    averageDailySales: 8,
    daysToRestock: 3,
    imageUrl: 'https://placehold.co/400x400',
    imageHint: 'soda can',
  },
  {
    id: 'prod_005',
    name: 'Água Mineral com Gás',
    quantity: 200,
    expirationDate: '2025-08-01',
    averageDailySales: 30,
    daysToRestock: 2,
    imageUrl: 'https://placehold.co/400x400',
    imageHint: 'water bottle',
  },
  {
    id: 'prod_006',
    name: 'Suco de Laranja Integral',
    quantity: 40,
    expirationDate: '2024-09-10',
    averageDailySales: 5,
    daysToRestock: 4,
    imageUrl: 'https://placehold.co/400x400',
    imageHint: 'juice carton',
  },
    {
    id: 'prod_007',
    name: 'Vodka Premium',
    quantity: 25,
    expirationDate: '2028-06-01',
    averageDailySales: 3,
    daysToRestock: 7,
    imageUrl: 'https://placehold.co/400x400',
    imageHint: 'vodka bottle',
  },
  {
    id: 'prod_008',
    name: 'Champanhe Brut',
    quantity: 10,
    expirationDate: '2026-05-20',
    averageDailySales: 0.5,
    daysToRestock: 20,
    imageUrl: 'https://placehold.co/400x400',
    imageHint: 'champagne bottle',
  },
];
